### ISSUE TITLE
PDF creation failing

### ISSUE THREAD

**Issue by HolyMolyCowMan** [FavoriteCentaurMoe/Manga-Downloader#1]
Hi,
When downloading Attack on Titan chapter 108, the script incorrectly finds the amount of pages. This creates corrupt images causing the pdf creation to fail, crashing the script.

**Comment by HolyMolyCowMan** [comment]
I found a way to fix this but it results in the program being a lot slower when downloading. If we open the file and look at the first character we can decide whether there is an image there. If the first character is a "{" we can assume it's not a jpg. This works afaik

**Comment by FavoriteCentaurMoe** [comment]
Yeah it seems like my program only worked with .jpg files and attack on titan chapter 108 is .png 

Now I made it work with all image filetypes so it should work now. Thanks for letting me know!
